spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useOldAliasMetadataBehavior=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

logging:
  level:
    root: info
    com.dong1990.blog: debug
  file:
    name: log/blog-pro.log



